# Generated by Django 4.1.3 on 2022-11-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_ownership_status_item_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='ownership',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accept'), (3, 'Decline')], default=1),
        ),
    ]
