# Generated by Django 4.1.3 on 2022-11-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_item_status_ownership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Decline', 'Decline')], default='Pending', max_length=100),
        ),
    ]
