# Generated by Django 4.1.3 on 2022-11-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_ownership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accept'), (3, 'Decline')], default=1),
        ),
    ]
