# Generated by Django 4.1.3 on 2022-11-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_historicalownership_date_issued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalownership',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='date_issued',
        ),
    ]
