# Generated by Django 4.1.3 on 2022-11-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_historicalownership_date_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalownership',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
