# Generated by Django 4.1.3 on 2022-12-01 13:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_historicalownership_remarks_ownership_remarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ownership',
            new_name='AcceptedRequest',
        ),
        migrations.RenameModel(
            old_name='HistoricalOwnership',
            new_name='HistoricalAcceptedRequest',
        ),
        migrations.AlterModelOptions(
            name='historicalacceptedrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical accepted request', 'verbose_name_plural': 'historical accepted requests'},
        ),
    ]
