# Generated by Django 4.1.3 on 2022-12-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_ownership_acceptedrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedrequest',
            name='date_issued',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalacceptedrequest',
            name='date_issued',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
